language: python
python:
- '2.7'
- '3.6'
install:
- pip install codecov
- pip install --upgrade setuptools wheel
script:
- python setup.py install
- cd tests
- coverage run test_mlbox.py
after_success:
- codecov
