language: python
python:
- '2.7'
- '3.6'
install:
- pip install codecov
- pip install --upgrade setuptools wheel
- pip install --only-binary all -r python-package/requirements.txt
script:
- cd python-package
- python setup.py install
- cd ../tests
- coverage run test_mlbox.py
after_success:
- codecov
