language: python
python:
- '2.7'
- '3.6'
install:
- pip install coverage
- pip install codecov
- pip install pytest
- pip install --upgrade setuptools wheel
script:
- python setup.py install
- cd tests
- coverage run -m pytest
after_success:
- codecov
